from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import LeaveViewSet

# Create a router and register our viewset with it.
router = DefaultRouter()
# basename='leave' is helpful to distinguish URL names if the queryset doesn't define it clearly.
router.register(r'leaves', LeaveViewSet, basename='leave')

urlpatterns = [
    # Include the URLs generated by the router.
    path('', include(router.urls)),
]
